  ##############################
 #///Silvware's picom config///#
 #############################

 ###############################
#           Backend           #
##############################

#Recommended Backends: "xrender" or "glx".
#GLX is based on OpenGL, more resource intensive but has better effects.
#meanwhile xrender is using the integrated X11 renderer, more lightweight on resource#usage.

backend = "xrender";

 ###############################
#             glx             #
##############################

#the glx section is specific for some tweaks for the glx backend, not really necesaryto modify unless you want something more specific.

#there's more info on the actual wiki of picom if you want to make more "deep" mods.

#use damage is disabled to avoid artifacts painting under blur transparent windows.
use-damage = false;

 ###############################
#           Shadows           #
##############################

#Enables/Disables client-side shadows on windows
shadow = false;

#Blur radius for shadows.
shadow-radius = 12;

#horizontal offset for shadows (negative for left, positive for right.)
shadow-offset-x = -15;

#vertical offset for shadows. (negative for top, positive for below.)
shadow-offset-y = -35;

#translucency for shadows.
shadow-opacity = 0.7;

#set if you want dif coloured shadows.
#shadow-red = 0.0;
#shadow-green = 0.0;
#shadow-blue = 0.0;

 ##########################
#         Opacity        #
#########################

#value for inactive windows
#inactive-opacity = 0.6;
#value for frame opacity
#frame-opacity = 0.7;
#value for active windows.
#active-opacity = 1.0;

 #########################
#         Fading        #
########################

 ########################
#    ROUNDED CORNERS   #
#######################

#var that controls the roundness of windows.
corner-radius = 10

 ########################
#       BLURRING       #
#######################  

#########################
#      ANIMATIONS      #               
#######################

animations = ({
        triggers = ["close", "hide"];
	preset = "fly-out";
	direction = "right";
	duration = 0.5;
}, {
  triggers = ["open", "show"];
  preset = "fly-in"
  direction = "down";
  duration = 0.5;
           
})

 #######################
#        RULES        #
######################

rules = (
        {match = "focused"; opacity = 1; },
	{match = "!focused"; opacity = 0.85; },
	{match = "popup_menu"; opacity = 0.7; },
	{match = "dropdown_menu"; opacity = 0.7; },
	{match = "alacritty"; opacity = 0.9},)

